version: '3.7'

services:
  repo_manager:
    build: ../gitbeam.repo.manager
    ports:
      - "8001:8001"
    depends_on:
      - gateway

  commit_monitor:
    build: ../gitbeam.commit.monitor
    ports:
      - "8002:8002"
    depends_on:
      - gateway

  gateway:
    build: .
    ports:
      - "8080:8080"
