version: '3.7'

services:
  repo_manager:
    build: ../gitbeam.repo.manager
    ports:
      - "8001:8001"
    depends_on:
      - gateway
    environment:
      - PORT=8001
      - DATABASE_NAME=repo.db

  commit_monitor:
    build: ../gitbeam.commit.monitor
    ports:
      - "8002:8002"
    depends_on:
      - gateway
    environment:
      - PORT=8002
      - COMMIT_DATABASE_NAME=commit.db
      - CRON_DATABASE_NAME=cron.db

  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - COMMIT_MONITOR_URL=commit_monitor:8002
      - REPO_MANAGER_URL=repo_manager:8001

