// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gitbeam/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockDataStore is a mock of DataStore interface.
type MockDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockDataStoreMockRecorder
}

// MockDataStoreMockRecorder is the mock recorder for MockDataStore.
type MockDataStoreMockRecorder struct {
	mock *MockDataStore
}

// NewMockDataStore creates a new mock instance.
func NewMockDataStore(ctrl *gomock.Controller) *MockDataStore {
	mock := &MockDataStore{ctrl: ctrl}
	mock.recorder = &MockDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStore) EXPECT() *MockDataStoreMockRecorder {
	return m.recorder
}

// GetCommitBySHA mocks base method.
func (m *MockDataStore) GetCommitBySHA(ctx context.Context, owner models.OwnerAndRepoName, sha string) (*models.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitBySHA", ctx, owner, sha)
	ret0, _ := ret[0].(*models.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitBySHA indicates an expected call of GetCommitBySHA.
func (mr *MockDataStoreMockRecorder) GetCommitBySHA(ctx, owner, sha interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitBySHA", reflect.TypeOf((*MockDataStore)(nil).GetCommitBySHA), ctx, owner, sha)
}

// GetLastCommit mocks base method.
func (m *MockDataStore) GetLastCommit(ctx context.Context, owner *models.OwnerAndRepoName, startTime *time.Time) (*models.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommit", ctx, owner, startTime)
	ret0, _ := ret[0].(*models.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommit indicates an expected call of GetLastCommit.
func (mr *MockDataStoreMockRecorder) GetLastCommit(ctx, owner, startTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommit", reflect.TypeOf((*MockDataStore)(nil).GetLastCommit), ctx, owner, startTime)
}

// GetRepoByOwner mocks base method.
func (m *MockDataStore) GetRepoByOwner(ctx context.Context, owner *models.OwnerAndRepoName) (*models.Repo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoByOwner", ctx, owner)
	ret0, _ := ret[0].(*models.Repo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoByOwner indicates an expected call of GetRepoByOwner.
func (mr *MockDataStoreMockRecorder) GetRepoByOwner(ctx, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoByOwner", reflect.TypeOf((*MockDataStore)(nil).GetRepoByOwner), ctx, owner)
}

// GetTopCommitAuthors mocks base method.
func (m *MockDataStore) GetTopCommitAuthors(ctx context.Context, filter models.CommitFilters) ([]*models.TopCommitAuthor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCommitAuthors", ctx, filter)
	ret0, _ := ret[0].([]*models.TopCommitAuthor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCommitAuthors indicates an expected call of GetTopCommitAuthors.
func (mr *MockDataStoreMockRecorder) GetTopCommitAuthors(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCommitAuthors", reflect.TypeOf((*MockDataStore)(nil).GetTopCommitAuthors), ctx, filter)
}

// ListCommits mocks base method.
func (m *MockDataStore) ListCommits(ctx context.Context, filter models.CommitFilters) ([]*models.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommits", ctx, filter)
	ret0, _ := ret[0].([]*models.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommits indicates an expected call of ListCommits.
func (mr *MockDataStoreMockRecorder) ListCommits(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommits", reflect.TypeOf((*MockDataStore)(nil).ListCommits), ctx, filter)
}

// ListRepos mocks base method.
func (m *MockDataStore) ListRepos(arg0 context.Context) ([]*models.Repo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepos", arg0)
	ret0, _ := ret[0].([]*models.Repo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepos indicates an expected call of ListRepos.
func (mr *MockDataStoreMockRecorder) ListRepos(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepos", reflect.TypeOf((*MockDataStore)(nil).ListRepos), arg0)
}

// SaveCommit mocks base method.
func (m *MockDataStore) SaveCommit(ctx context.Context, payload *models.Commit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommit", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommit indicates an expected call of SaveCommit.
func (mr *MockDataStoreMockRecorder) SaveCommit(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommit", reflect.TypeOf((*MockDataStore)(nil).SaveCommit), ctx, payload)
}

// StoreRepository mocks base method.
func (m *MockDataStore) StoreRepository(ctx context.Context, payload *models.Repo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRepository", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRepository indicates an expected call of StoreRepository.
func (mr *MockDataStoreMockRecorder) StoreRepository(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRepository", reflect.TypeOf((*MockDataStore)(nil).StoreRepository), ctx, payload)
}

// MockCronServiceStore is a mock of CronServiceStore interface.
type MockCronServiceStore struct {
	ctrl     *gomock.Controller
	recorder *MockCronServiceStoreMockRecorder
}

// MockCronServiceStoreMockRecorder is the mock recorder for MockCronServiceStore.
type MockCronServiceStoreMockRecorder struct {
	mock *MockCronServiceStore
}

// NewMockCronServiceStore creates a new mock instance.
func NewMockCronServiceStore(ctrl *gomock.Controller) *MockCronServiceStore {
	mock := &MockCronServiceStore{ctrl: ctrl}
	mock.recorder = &MockCronServiceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCronServiceStore) EXPECT() *MockCronServiceStoreMockRecorder {
	return m.recorder
}

// DeleteCronTask mocks base method.
func (m *MockCronServiceStore) DeleteCronTask(ctx context.Context, owner models.OwnerAndRepoName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCronTask", ctx, owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCronTask indicates an expected call of DeleteCronTask.
func (mr *MockCronServiceStoreMockRecorder) DeleteCronTask(ctx, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCronTask", reflect.TypeOf((*MockCronServiceStore)(nil).DeleteCronTask), ctx, owner)
}

// GetCronTask mocks base method.
func (m *MockCronServiceStore) GetCronTask(ctx context.Context, owner models.OwnerAndRepoName) (*models.CronTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCronTask", ctx, owner)
	ret0, _ := ret[0].(*models.CronTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCronTask indicates an expected call of GetCronTask.
func (mr *MockCronServiceStoreMockRecorder) GetCronTask(ctx, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCronTask", reflect.TypeOf((*MockCronServiceStore)(nil).GetCronTask), ctx, owner)
}

// ListCronTask mocks base method.
func (m *MockCronServiceStore) ListCronTask(ctx context.Context) ([]*models.CronTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCronTask", ctx)
	ret0, _ := ret[0].([]*models.CronTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCronTask indicates an expected call of ListCronTask.
func (mr *MockCronServiceStoreMockRecorder) ListCronTask(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCronTask", reflect.TypeOf((*MockCronServiceStore)(nil).ListCronTask), ctx)
}

// SaveCronTask mocks base method.
func (m *MockCronServiceStore) SaveCronTask(ctx context.Context, task models.CronTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCronTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCronTask indicates an expected call of SaveCronTask.
func (mr *MockCronServiceStoreMockRecorder) SaveCronTask(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCronTask", reflect.TypeOf((*MockCronServiceStore)(nil).SaveCronTask), ctx, task)
}
